version: 2
updates:
  # GitHub Actions workflows ke updates ke liye
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Python dependencies (agar root ya server folder me requirements.txt ho)
  - package-ecosystem: "pip"
    directory: "/" # Agar requirements.txt 'server/' me hai to "/server" likhein
    schedule:
      interval: "weekly"

  # Frontend / Dashboard (agar package.json 'dashboard/' me hai)
  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "weekly"
